version: '3.5'
services:
  flask-app:
    build: .
    hostname: flask-app
    depends_on: 
      - db
    expose:
      - "5000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'


  db:
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
      
